"""
Mega base de conhecimento — popula o banco com centenas de entradas ricas.
Execute: python -m condor.memory.mega_seeder
"""
from __future__ import annotations
from condor.memory.db import MemoryDB
from condor.config import load_config
import logging

log = logging.getLogger("condor.mega_seeder")

# ─────────────────────────────────────────────────────────────────────────────
# KNOWLEDGE BASE — cada entrada é texto denso injetável no contexto do Condor
# ─────────────────────────────────────────────────────────────────────────────

KNOWLEDGE = [

# ══════════════════════════════════════════════════════════════════════════════
# PSICOLOGIA PROFUNDA
# ══════════════════════════════════════════════════════════════════════════════

("psicologia:autoestima",
"""Autoestima é a avaliação que uma pessoa faz de si mesma — não é vaidade, é a base de tudo. Pessoas com autoestima saudável conseguem dizer não sem culpa, pedir ajuda sem vergonha, receber crítica sem desmoronar e errar sem se destruir. Autoestima baixa vem geralmente de infância: críticas constantes, amor condicional, ausência de validação emocional. O resultado adulto é alguém que trabalha demais para ser aprovado, tolera maus tratos porque "acha que merece", sabota conquistas quando se sente indigno do sucesso. Autoestima não se constrói com afirmações no espelho — se constrói com ação: fazer o que você prometeu a si mesmo, sustentar seus valores mesmo quando é difícil, e perceber que sobreviveu às coisas que achava que não conseguiria. A relação entre autoestima e relacionamentos é direta: você atrai e tolera o que acha que merece. Quem não se respeita aceita desrespeito dos outros. Terapia cognitiva, especialmente TCC e Terapia do Esquema, são as mais eficazes para trabalhar crenças nucleares de incapacidade e indignidade."""),

("psicologia:ansiedade",
"""Ansiedade é o sistema de alarme do cérebro funcionando em excesso. Em doses normais é útil — te faz preparar para o vestibular, te impede de atravessar a rua sem olhar. O problema é quando o alarme dispara sem ameaça real, ou quando a resposta é desproporcional. A ansiedade opera no futuro: é o medo antecipado de algo que ainda não aconteceu e talvez nunca aconteça. O loop ansioso é: pensamento catastrófico → tensão corporal → evitação → alivio temporário → reforço do medo. A evitação é o pior remédio para ansiedade — ela alivia no curto prazo e piora no longo. O tratamento mais eficaz é a exposição gradual: enfrentar o que causa ansiedade de forma controlada. Ansiedade generalizada, social, pânico, fobia específica, TOC e TEPT são categorias distintas mas compartilham o mecanismo de alarme hiperativo. Medicação (ISRS, IRSN) reduz o ruído de fundo. Terapia (TCC, ACT) muda a relação com os pensamentos. Exercício físico é um dos ansiolíticos mais potentes que existem. Respiração diafragmática ativa o parassimpático e interrompe a resposta de luta-ou-fuga em segundos."""),

("psicologia:depressao",
"""Depressão não é tristeza — é a ausência de sentido e de energia para qualquer coisa. A tristeza passa, a depressão persiste. Sintomas centrais: humor deprimido na maior parte do dia, perda de prazer em coisas que antes davam prazer (anedonia), fadiga extrema, dificuldade de concentração, pensamentos negativos automáticos, alterações de sono e apetite, e nos casos graves, pensamentos de morte. Depressão tem componente biológico forte — não é fraqueza, não é escolha, não é falta de força de vontade. Serotonina, dopamina e noradrenalina estão disfuncionais. Trauma, perda, estresse crônico e genética contribuem. O paradoxo da depressão: o que mais ajuda (exercício, sair de casa, ver pessoas, fazer coisas) é exatamente o que a depressão torna impossível. Por isso o tratamento profissional é essencial. Antidepressivos (ISRS são primeira linha) levam 2-4 semanas para agir. TCC é tão eficaz quanto medicação para casos moderados. A combinação dos dois é mais eficaz que qualquer um isolado. Depressão não tratada piora — não é "fase que passa". Quem está com depressão precisa de apoio concreto, não de conselhos sobre "pensar positivo"."""),

("psicologia:trauma",
"""Trauma é qualquer experiência que o sistema nervoso não conseguiu processar adequadamente. Não é o evento em si — é o que ficou registrado no corpo e na mente como ameaça permanente. TEPT (Transtorno de Estresse Pós-Traumático) é a forma mais conhecida, mas trauma pode ser sutil: rejeição crônica na infância, humilhação repetida, ambiente familiar imprevisível, negligência emocional. Trauma complexo (C-TEPT) vem de exposição prolongada — abuso, negligência, violência doméstica. O corpo guarda o trauma: tensão muscular crônica, hipervigilância, reações exageradas a estímulos neutros, dissociação. O cérebro traumatizado funciona diferente: amígdala hiperativa (alarme constante), córtex pré-frontal hipoativo (menos raciocínio), hipocampo alterado (memória fragmentada). Tratamentos baseados em evidência: EMDR (reprocessamento por movimentos oculares), Terapia Somatic Experiencing, TCC focada no trauma, terapia de exposição prolongada. Peter Levine, Bessel van der Kolk ("O Corpo Guarda as Marcas") e Judith Herman são referências fundamentais. Trauma não processado se manifesta em relacionamentos: repetição de padrões, dificuldade de intimidade, explosões emocionais aparentemente sem motivo."""),

("psicologia:apego",
"""A teoria do apego, de John Bowlby, explica como os vínculos formados na infância moldam todos os relacionamentos adultos. Quatro estilos de apego: Seguro (cuidador consistente e responsivo — adulto confia, se conecta sem medo de abandono), Ansioso/Ambivalente (cuidador inconsistente — adulto tem medo de abandono, é clínico e necessitado), Evitativo (cuidador rejeitador ou distante — adulto evita intimidade, prioriza independência como defesa), Desorganizado (cuidador foi fonte de medo — adulto tem relacionamentos caóticos e contraditórios). O estilo de apego não é destino fixo — pode mudar com relacionamentos seguros, terapia e autoconhecimento. A dinâmica ansioso-evitativo é a mais comum em relacionamentos conflituosos: o ansioso persegue, o evitativo recua, o ansioso persegue mais, o evitativo some. Nenhum dos dois está errado — são adaptações a infâncias diferentes. Apego seguro adulto se constrói: consistência nas respostas emocionais, capacidade de regular as próprias emoções, comunicação honesta sobre necessidades."""),

("psicologia:tcc",
"""Terapia Cognitivo-Comportamental (TCC) é a abordagem psicoterapêutica com maior base científica. Premissa central: não são os eventos que nos perturbam, mas a interpretação que fazemos deles (Epicteto já dizia isso). Pensamentos automáticos negativos são o alvo principal — crenças que surgem automaticamente e distorcem a realidade. Distorções cognitivas mais comuns: catastrofização (sempre imaginar o pior), leitura mental (achar que sabe o que o outro pensa), personalização (tomar tudo como culpa sua), pensamento tudo-ou-nada (sem meio-termo), abstração seletiva (focar só no negativo). A TCC ensina a identificar esses padrões, questionar as evidências, e construir pensamentos mais realistas. Além de cognitivo, o componente comportamental é crucial: mudança de comportamento antes de mudança de sentimento. Agir "como se" o estado desejado fosse real cria o estado. TCC é estruturada, com prazo definido (12-20 sessões para maioria dos casos), orientada a problemas específicos. É altamente eficaz para ansiedade, depressão, TOC, fobias, insônia, dor crônica e vários outros quadros."""),

("psicologia:narcisismo",
"""Narcisismo patológico (Transtorno de Personalidade Narcisista) é muito diferente de autoconfiança saudável. O narcisista tem grandiosidade (senso inflado de importância), necessidade constante de admiração e falta de empatia. Por baixo disso existe autoestima extremamente frágil — qualquer crítica é vivida como ataque existencial. O narcisismo vem de infância: ou de supervalorização (criança tratada como especial demais) ou de rejeição e humilhação (grandiosidade como defesa). Tipos: Grandioso (ostensivo, dominante, busca admiração abertamente) e Vulnerável/Encoberto (sensível, ressentido, vitimismo). Relacionamento com narcisista é destrutivo: ciclo de idealização-desvalorização-descarte (love bombing, depois crítica e controle, depois abandono). Gaslighting é marca registrada: manipulação que faz a vítima duvidar da própria percepção. Narcisistas raramente buscam ajuda — quando chegam à terapia, é por outra razão ou pressão externa. Terapia é longa e difícil. Para quem está em relacionamento com narcisista: o padrão não muda por amor, por tolerância ou por ser melhor parceiro. O único movimento eficaz é sair."""),

("psicologia:inteligencia_emocional",
"""Inteligência emocional (IE) é a capacidade de reconhecer, entender, usar e gerenciar emoções — as próprias e as dos outros. Daniel Goleman popularizou o conceito com 5 componentes: autoconsciência (saber o que sente), autorregulação (gerenciar reações), motivação (impulso interno), empatia (sentir o outro), habilidades sociais (navegar relacionamentos). IE é mais preditiva de sucesso em vida do que QI. Pessoas com IE alta: conseguem pausar entre estímulo e resposta, identificam emoções com precisão (não "tô mal" mas "tô com vergonha"), não são dominadas pelos próprios estados emocionais, conseguem regular sem suprimir. Regulação emocional não é não sentir — é sentir sem ser engolido. Estratégias: nomeação da emoção (naming it to tame it — nomear reduz a intensidade), reavaliação cognitiva, aceitação sem julgamento, distância psicológica ("como eu veria isso em 5 anos?"). IE se desenvolve — não é fixa como QI. Terapia, meditação, journaling e feedback honesto de pessoas próximas são os melhores caminhos."""),

("psicologia:vieses_cognitivos",
"""O cérebro humano opera por atalhos (heurísticas) que economizam energia mas criam erros sistemáticos de julgamento. Principais vieses: Viés de confirmação (busca só informações que confirmam o que já acredita, ignora o resto), Efeito ancoragem (primeira informação recebida ancora todas as avaliações seguintes), Heurística da disponibilidade (superestima probabilidade de eventos que vêm facilmente à mente — acidentes de avião parecem mais comuns do que são), Viés do presente (prefere recompensas imediatas a maiores futuras), Efeito halo (uma qualidade positiva contamina avaliação de todo o resto), Viés de atribuição (sucesso = mérito próprio; fracasso = culpa externa — e o inverso para os outros), Efeito Dunning-Kruger (incompetentes superestimam competência; especialistas subestimam), Falácia do custo irrecuperável (continuar investindo em algo ruim porque "já gastou demais para parar"), Viés de otimismo (acha que coisas ruins só acontecem com outros). Conhecer os vieses não elimina-os — mas cria um segundo olhar crítico antes de decidir."""),

("psicologia:motivacao",
"""Motivação tem dois tipos fundamentais: intrínseca (motivada pelo próprio interesse, prazer e propósito) e extrínseca (por recompensa externa ou punição). A teoria da autodeterminação (Deci e Ryan) identifica três necessidades psicológicas básicas que, quando satisfeitas, sustentam motivação intrínseca duradoura: Autonomia (sentir que escolhe, não que é forçado), Competência (sentir que cresce e é eficaz), Pertencimento (sentir que está conectado a outros). Motivação por medo funciona no curto prazo mas esgota — produz ansiedade, não engajamento. Motivação por propósito é sustentável. O paradoxo da motivação: esperar "estar motivado" para agir é ao contrário — a ação cria a motivação. Agir primeiro, sentir depois. Flow (Csikszentmihalyi) é o estado de absorção total numa tarefa quando desafio e habilidade estão equilibrados — zona onde tempo some e performance é máxima. Procrastinação não é preguiça — é regulação emocional: evita a tarefa para evitar emoções negativas ligadas a ela (medo de falhar, perfeccionismo, tédio). Tratamento da procrastinação: reduzir a aversão da tarefa, não aumentar a força de vontade."""),

("psicologia:personalidade",
"""Personalidade é o padrão estável de como uma pessoa pensa, sente e se comporta. O modelo mais robusto cientificamente é os Big Five (OCEAN): Abertura à experiência (curiosidade intelectual, criatividade, tolerância à ambiguidade), Conscienciosidade (organização, disciplina, planejamento), Extroversão (sociabilidade, assertividade, energia no contato social), Amabilidade (cooperação, empatia, tendência a evitar conflito), Neuroticismo (tendência à instabilidade emocional, ansiedade, irritabilidade). Personalidade tem forte base genética (50-70%) mas é moldada por experiência. É relativamente estável na vida adulta mas não imutável — trauma, terapia, experiências intensas e esforço consciente mudam traços. MBTI (Myers-Briggs) é popular mas tem validade científica questionável. OCEAN é mais replicável e preditivo de comportamento real. Transtornos de personalidade (cluster A, B, C) são padrões extremamente rígidos que causam sofrimento significativo — borderline, narcisista, antissocial, evitativo, obsessivo-compulsivo, entre outros."""),

("psicologia:terapia_esquema",
"""Terapia do Esquema (Jeffrey Young) é uma extensão da TCC que trabalha os padrões mais profundos e enraizados da personalidade. Esquemas são crenças nucleares sobre si mesmo e o mundo, formadas na infância quando necessidades emocionais básicas não foram atendidas. 18 esquemas disfuncionais divididos em 5 domínios: Desconexão e Rejeição (abandono, desconfiança, privação emocional, defectividade, isolamento), Autonomia Prejudicada (dependência, vulnerabilidade, emaranhamento, fracasso), Limites Prejudicados (arrogo, autocontrole insuficiente), Orientação para o Outro (subjugação, autossacrifício, busca de aprovação), Supervigilância e Inibição (negativismo, inibição emocional, padrões inflexíveis, punição). Cada esquema tem modos de enfrentamento: rendição (aceita o esquema como verdade), evitação (foge de situações que o ativam), compensação (age de forma oposta ao esquema). O trabalho terapêutico: reparentalização limitada, trabalho com cadeiras (diálogo entre partes internas), imagerial. Indicada especialmente para transtornos de personalidade e casos que não responderam à TCC padrão."""),

("psicologia:mindfulness",
"""Mindfulness é atenção plena: observar intencionalmente o momento presente sem julgamento. Não é esvaziar a mente — é observar os pensamentos como eventos mentais, não como fatos. A mente divaga 47% do tempo, segundo pesquisa de Harvard, e isso está associado a menor bem-estar. Mindfulness reduz essa ruminação. Evidências científicas sólidas para: redução de ansiedade e depressão, melhora de regulação emocional, redução de dor crônica, melhora de foco e memória de trabalho, redução de reatividade ao estresse. MBSR (Mindfulness-Based Stress Reduction, Jon Kabat-Zinn) e MBCT (Mindfulness-Based Cognitive Therapy) são programas com mais de 40 anos de pesquisa. Prática básica: foca na respiração, mente divaga, percebe, volta — sem drama. A percepção que voltou É o mindfulness. Não existe falhar em meditação. Mudanças neurológicas observáveis com 8 semanas de prática regular: aumento de cinza no córtex pré-frontal, redução de atividade na amígdala. Mindfulness não é passividade — é ver com clareza para agir com inteligência."""),

# ══════════════════════════════════════════════════════════════════════════════
# EMOÇÕES HUMANAS
# ══════════════════════════════════════════════════════════════════════════════

("emocao:raiva",
"""Raiva é uma emoção primária de proteção — sinaliza que um limite foi violado, uma injustiça foi cometida ou uma necessidade não foi atendida. Não é errada: é informação. O problema é a expressão descontrolada ou a supressão crônica. Raiva suprimida vira ressentimento, depressão, doenças psicossomáticas. Raiva explosiva destrói relacionamentos e cria arrependimento. A raiva saudável: reconhecida, nomeada, comunicada assertivamente ("eu fiquei com raiva quando você fez X porque..."). Fisiologicamente: adrenalina e noradrenalina disparam, frequência cardíaca sobe, músculos tensionam — o corpo se prepara para luta. Esperar 20 minutos antes de responder em momento de raiva intensa permite que o cortisol baixe. Exercício físico é o melhor canal de descarga biológica. Raiva crônica (hostilidade) está associada a doenças cardiovasculares. Raiva como defesa: muitas vezes raiva é medo ou dor disfarçados — é mais fácil ficar bravo do que admitir que está assustado ou magoado."""),

("emocao:medo",
"""Medo é a resposta de proteção mais primitiva do cérebro — a amígdala o processa antes mesmo do córtex consciente perceber o estímulo. Útil quando há ameaça real. Destrutivo quando a ameaça é imaginada, exagerada ou passada. Medo do futuro (ansiedade) é diferente de medo do presente (reação aguda). Medos mais comuns: de falhar, de rejeição, de abandono, de não ser suficiente, de morrer, de perder o controle, de julgamento. O medo de julgamento social é um dos mais paralisantes — humanos são animais sociais, exclusão do grupo era morte no passado evolutivo. Então o cérebro trata crítica social como ameaça física. Enfrentar o medo (exposição) é a única forma de reduzir sua poder — evitação mantém e amplifica. Coragem não é ausência de medo — é agir apesar do medo. Diferenciar medo de sinal útil e medo de padrão mental é essencial: o corpo tem um jeito de sentir ameaça real vs. ameaça imaginada (a segunda costuma ser mais difusa e sem objeto concreto)."""),

("emocao:vergonha",
"""Vergonha é a emoção mais dolorosa e mais escondida. Diferença crucial: culpa é "eu fiz algo ruim", vergonha é "eu sou ruim". Culpa pode motivar reparação — vergonha só paralisa. Vergonha floresce no segredo e murcha quando colocada em palavras (Brené Brown). O antídoto da vergonha é vulnerabilidade: falar sobre ela a alguém de confiança. Vergonha internalizada na infância (fui chamado de burro, feio, inútil, nunca faço nada certo) vira crença nuclear no adulto. Pessoas com vergonha crônica oscilam entre dois extremos: encolhimento total ou grandiosidade defensiva. A vergonha ataca a identidade, não o comportamento — por isso é tão difícil de trabalhar. Narcisismo é frequentemente vergonha escondida atrás de grandiosidade. Perfeccionismo é medo da vergonha — se eu for perfeito, ninguém me criticará. Resistência a pedir ajuda é vergonha — pedir ajuda "prova" a incapacidade. Trabalho com vergonha em terapia: nomear, situar na história, separar "o que fiz" de "quem sou"."""),

("emocao:solidao",
"""Solidão é a discrepância entre conexão desejada e conexão real. Não é estar sozinho — é sentir-se desconectado. Pessoas cercadas de gente podem ser profundamente solitárias. Solidão crônica tem efeitos físicos devastadores: equivale a fumar 15 cigarros por dia em risco de saúde (estudo de Julianne Holt-Lunstad). Aumenta cortisol, prejudica imunidade, perturba o sono, acelera declínio cognitivo. Solidão epidêmica moderna: tecnologia conecta e ao mesmo tempo cria ilusão de conexão sem substância real. Muitos relacionamentos superficiais mas nenhuma intimidade. Paradoxo da solidão: quando solitário, o cérebro entra em modo de ameaça social — torna-se mais desconfiado, mais sensível a rejeição, o que dificulta a conexão que precisa. Sair da solidão: buscar comunidade de propósito (não só de conveniência), cultivar vulnerabilidade seletiva, preferir qualidade a quantidade de conexões, desenvolver relação com si mesmo (solidão ≠ solitude saudável)."""),

("emocao:culpa",
"""Culpa funcional (proporcional e baseada em valor) é moralmente necessária — sinaliza que você agiu contra seus princípios e motiva reparação. Culpa disfuncional é desproporcional, generalizada, sem objeto específico, e frequentemente introjetada de críticas externas. Culpa crônica é autoagressão disfarçada. Quem cresceu com pais críticos ou em ambientes religiosos punitivos tende a carregar culpa como estado permanente, não como resposta situacional. Culpa vs. responsabilidade: responsabilidade é reconhecer o impacto dos próprios atos e repará-los. Culpa é ficar ruminando o erro sem ação. Uma vez que reparou o que era para reparar, continuar se punindo não serve mais a ninguém. Autoperdão não é minimizar o que fez — é reconhecer, reparar e seguir. Pessoas com muita culpa frequentemente se tornam incapazes de receber cuidado — sentem que não merecem."""),

("emocao:amor",
"""Amor não é um sentimento único — é um conjunto de estados distintos. Helen Fisher identificou três sistemas neurais: Desejo (testosterona, libido, atração física), Atração Romântica (dopamina, noradrenalina — o "apaixonamento", o foco obsessivo no outro) e Apego (ocitocina, vasopressina — vínculo de longo prazo, segurança, parceria). Apaixonamento tem duração biológica de 18 meses a 3 anos — depois o cérebro normaliza os níveis de dopamina e a "paixão louca" cede. Isso não é o fim do amor — é o começo do amor real. Relacionamentos que só dependem da fase de atração não sobrevivem à normalização. Amor maduro inclui: respeito, companheirismo, atração sustentada (não constante), comunicação, escolha consciente de estar. Os cinco idiomas do amor (Gary Chapman): palavras de afirmação, tempo de qualidade, presença física, atos de serviço, presentes. Pessoas têm idiomas preferidos — falar o idioma do outro é fundamental. Amor sem respeito não é amor. Amor que controla não é amor."""),

("emocao:ciume",
"""Ciúme é a emoção de ameaça a um vínculo valioso — medo de perder para um rival. É universal, tem base evolutiva (proteção do parceiro reprodutivo e dos recursos), mas varia enormemente em intensidade e expressão. Ciúme saudável: sinal de que o relacionamento importa, comunicado honestamente, processado internamente. Ciúme patológico: desconfiança irracional, comportamento controlador, invasão de privacidade, isolamento da parceira. Ciúme patológico é sobre insegurança própria, não sobre o comportamento do outro. O ciumento persegue o celular do parceiro não porque o parceiro é infiel — é porque o ciumento não se sente suficiente. Ciúme retroativo (ciúme de passado do parceiro) é tortura auto-infligida baseada em comparação. Possessividade disfarçada de amor: "sou assim porque te amo demais" é manipulação, não amor. Tratar ciúme: trabalho com autoestima, com estilo de apego ansioso, e com comunicação não-violenta sobre inseguranças."""),

("emocao:gratidao",
"""Gratidão é uma das emoções com maior impacto mensurável no bem-estar. Pesquisa de Robert Emmons: gratidão regular aumenta felicidade subjetiva em 25%, melhora qualidade do sono, aumenta energia, reduz depressão. Não é positividade forçada — é atenção deliberada ao que está bom enquanto o negativo também existe. Diário de gratidão funciona melhor quando específico e irregular (não mecânico): "hoje fui grato por X porque Y" tem mais impacto que listar 3 itens genéricos no piloto automático. Gratidão muda o foco atencional do que falta para o que há — o cérebro é wired para negatividade (negativity bias), então gratidão deliberada é um contra-treino. Expressar gratidão ao outro (carta de gratidão, agradecimento direto) tem efeito amplificado — tanto para quem expressa quanto para quem recebe. Gratidão não é submissão nem resignação com o que está errado — coexiste com crítica, ambição e desejo de mudança."""),

("emocao:tristeza",
"""Tristeza é a resposta emocional à perda — de pessoa, de relacionamento, de sonho, de versão de si mesmo, de possibilidade. É necessária, não é fraqueza. Suprimir tristeza cria depressão — a tristeza não processada fica estocada. Luto é o processo de integrar uma perda. Não tem prazo fixo, não tem etapas lineares. O modelo de Kübler-Ross (negação, raiva, barganha, depressão, aceitação) descreve elementos possíveis, não uma sequência obrigatória. Luto pode ser por morte, mas também por divórcio, fim de emprego, diagnóstico, fim de amizade, mudança de cidade. A cultura ocidental é avessa ao luto — pressiona por recuperação rápida, tabu de mostrar sofrimento. "Ficar bem" rápido demais muitas vezes significa não processar. Tristeza pede: ser sentida, expressada (chorar tem função fisiológica real — elimina hormônios de estresse), compartilhada com alguém de confiança, e tempo."""),

# ══════════════════════════════════════════════════════════════════════════════
# RELACIONAMENTOS
# ══════════════════════════════════════════════════════════════════════════════

("relacionamento:comunicacao",
"""Comunicação em relacionamento é a diferença entre conexão e conflito crônico. Marshall Rosenberg desenvolveu a Comunicação Não-Violenta (CNV): 4 componentes — Observação (o que aconteceu, sem julgamento), Sentimento (o que você sentiu), Necessidade (o que você precisava), Pedido (o que você quer que mude). Diferença entre "você sempre me ignora" (julgamento/ataque) e "quando você não respondeu ontem, eu me senti invisível — preciso sentir que sou prioridade — posso te pedir que avise quando estiver ocupado?" (CNV). Escuta ativa não é esperar sua vez de falar — é entender o que o outro realmente está dizendo, inclusive o que não está sendo dito. Validação emocional não significa concordar — significa reconhecer que o sentimento faz sentido dado o ponto de vista do outro. Crítica constante destrói relacionamentos — ratio de Gottman: 5 interações positivas para cada negativa é o mínimo para relacionamento saudável. Meta-comunicação (falar sobre como vocês comunicam) é habilidade rara e poderosa."""),

("relacionamento:conflito",
"""Conflito é inevitável em qualquer relacionamento próximo. O problema não é conflitar — é como conflitar. John Gottman identificou os "Quatro Cavaleiros do Apocalipse" — padrões que preveem separação com 93% de precisão: Crítica (atacar o caráter, não o comportamento — "você é irresponsável" vs. "fiquei preocupado quando você esqueceu"), Desprezo (sarcasmo, olhar de superioridade, deboche — é o preditor mais forte de fim de relacionamento), Defensividade (negar responsabilidade, contra-atacar, vitimismo), Stonewalling (murar, se fechar, silêncio punitivo). Antídotos: reclamação específica sem ataque à pessoa, expressão de apreciação, assumir responsabilidade parcial, autorregulação antes de responder. Conflito produtivo: ataca o problema, não a pessoa. Momentos de repair (tentativas de desescalar no meio do conflito — humor, toque, admitir excesso) são o que separa casais que brigam e ficam dos que brigam e se destroem. Brigar sobre o mesmo assunto repetidamente indica que o problema real não está sendo endereçado."""),

("relacionamento:terminos",
"""Término de relacionamentos é uma das experiências mais dolorosas da vida adulta — pesquisas mostram que rejeição romântica ativa as mesmas regiões cerebrais que dor física. Isso não é metáfora. Luto de relacionamento tem fases reais: choque, negação, raiva, barganha ("e se eu mudar?"), depressão, aceitação. Não é linear. O no contact (sem contato com o ex) funciona porque o cérebro precisa de tempo sem estímulo para reduzir o craving — como desintoxicação. Mídias sociais tornam a separação mais difícil: acesso constante a fotos, status, sinais de quem o outro está com agora. Nostalgia após término tende a idealizar o relacionamento — a mente apaga as partes ruins e guarda as boas. Ficar amigo do ex imediatamente raramente funciona — precisa de tempo de processamento. Terminar por covardia (ghosting, fuga, fazer o outro terminar) causa mais dano a ambos. Término honesto e direto, por mais doloroso, é mais respeitoso. Relacionamentos que terminam bem ensinaram algo — reconhecer o que foi genuíno sem negar o que não funcionou."""),

("relacionamento:intimidade",
"""Intimidade verdadeira é ser visto — não só o lado apresentável, mas o embaraçoso, o vulnerável, o contraditório — e ainda assim ser aceito. É o maior antídoto para solidão. Paradoxo da intimidade: exige vulnerabilidade, e vulnerabilidade exige risco de rejeição — exatamente o que mais queremos evitar. Pseudo-intimidade é comum: compartilhar muito sobre o passado mas evitar o presente real, discutir ideias mas não sentimentos, manter sexualidade ativa mas sem abertura emocional. Intimidade se constrói em camadas e ao longo do tempo — não é instantânea. O que cria intimidade: honestidade progressiva, ver o outro em seus momentos difíceis e não fugir, confiar segredos, pedir ajuda, mostrar fraqueza, estar presente quando o outro precisa. Intimidade fora dos relacionamentos românticos — com amigos, com família — é igualmente vital. Masculinidade tóxica é inimiga da intimidade entre homens: a cultura nega o espaço para vulnerabilidade masculina, criando solidão epidêmica entre homens. Intimidade com si mesmo (saber o que você sente, pensa, precisa) é pré-requisito para intimidade com outros."""),

("relacionamento:limites",
"""Limites não são muros para afastar as pessoas — são a definição de onde você termina e o outro começa. São necessidades e valores comunicados com clareza. Limite saudável: "eu não aceito ser gritado — se você gritar, eu saio da conversa até você se acalmar". Limite não é punição, é autopreservação. Dificuldade com limites vem de infância: criança ensinada que suas necessidades são inconvenientes, que dizer não é egoísmo, que amor significa se sacrificar. Adulto resultante: não sabe o que quer, diz sim quando quer dizer não, fica ressentido mas não fala, explode quando acumula demais. Limit setting tem dois passos: saber qual é o limite (consciência interna) e comunicá-lo (ação externa). O segundo é o difícil — medo de rejeição, de conflito, de ser visto como difícil. Relacionamentos onde limites não são respeitados não são relacionamentos seguros. Pessoas que reagem com raiva ou manipulação quando você coloca limites estão revelando exatamente por que o limite era necessário. Você não precisa de permissão para ter limites."""),

("relacionamento:codependencia",
"""Codependência é o padrão em que uma pessoa perde a si mesma em função do outro — seus sentimentos, identidade e bem-estar ficam completamente dependentes do estado do outro. Surgiu no contexto de famílias com dependentes químicos mas se aplica amplamente. Características: foco obsessivo nos problemas do outro enquanto ignora os próprios, controle disfarçado de cuidado ("preciso ajudá-lo para ele ficar bem"), dificuldade em separar sentimentos próprios dos do outro, identidade construída em ser necessário, medo extremo de abandono, borra fronteiras constantemente. Codependência não é amor — é ansiedade de apego disfarçada de amor. O codependente precisa que o outro precise dele. Relacionamentos codependentes são intensos mas destrutivos — um afoga o outro enquanto os dois se convencem de que é amor. Recuperação: reconstruir identidade própria, desenvolver interesses e vida independente, aprender a tolerar o desconforto de não controlar o outro, terapia focada em apego e diferenciação do self."""),

("relacionamento:infidelidade",
"""Infidelidade é complexa demais para ser reduzida a "safadeza". Esther Perel, maior terapeuta de casais da atualidade, descreve-a como geralmente sobre buscar algo que se perdeu no casamento — não necessariamente sexo, mas vida, novidade, identidade, afirmação. Tipos: infidelidade emocional (sem sexo mas com intimidade, segredos, priorização do outro), sexual (sem vínculo emocional), e os dois. O que destrói não é necessariamente o ato em si — é a mentira, a traição da confiança, o rearranjo da história compartilhada. Descobrir traição é um trauma: o parceiro que deveria ser a fonte de segurança se tornou a fonte do perigo. Casais que sobrevivem à infidelidade e reconstruem o relacionamento (não são poucos) geralmente conseguem porque: o parceiro infiel assume responsabilidade total (sem "mas você também"), há transparência radical por tempo suficiente, o relacionamento anterior é examinado honestamente (não para justificar, mas para entender), e há reconstrução da confiança por ações, não promessas. Permanecer não é fraqueza. Sair não é falta de amor. As duas podem ser decisões corretas dependendo do contexto."""),

# ══════════════════════════════════════════════════════════════════════════════
# FILOSOFIA APLICADA
# ══════════════════════════════════════════════════════════════════════════════

("filosofia:estoicismo",
"""Estoicismo é uma filosofia prática fundada em Atenas por Zenão de Cítio (300 a.C.) e desenvolvida por Epiteto, Marco Aurélio e Sêneca. Premissa central: não podemos controlar os eventos externos, apenas nossa resposta a eles. A dicotomia do controle divide tudo em duas categorias — o que depende de nós (julgamentos, intenções, desejos, aversões) e o que não depende (corpo, reputação, dinheiro, resultado das ações). Sofrer pelo que não controla é desperdício; focar no que controla é sabedoria. Premeditatio malorum: visualizar o pior que pode acontecer não para catastrofizar, mas para remover o poder do medo e preparar-se mentalmente. Amor fati (Nietzsche tomou dos estóicos): amar o destino — não resignar-se, mas abraçar o que acontece como necessário. Memento mori: lembrar da morte para valorizar o presente e não adiar o que importa. O Estoicismo influenciou diretamente a TCC — Aaron Beck reconhece Epicteto como precursor. Marco Aurélio escreveu Meditações para si mesmo — é o livro de filosofia prática mais poderoso já escrito por um homem no poder absoluto."""),

("filosofia:existencialismo",
"""Existencialismo parte da premissa que a existência precede a essência — você não vem ao mundo com propósito predefinido, você o cria. Sartre: estamos "condenados a ser livres" — a liberdade é inevitável e com ela vem a responsabilidade total. Ninguém mais pode ser responsabilizado pela sua vida. Camus trabalha o absurdo: a vida não tem sentido inerente, mas a resposta ao absurdo não é suicídio nem fé — é revolta, é criar sentido apesar do silêncio do universo. Sísifo empurrando a pedra eternamente pode ser imaginado feliz — a revolta contra o absurdo é em si a afirmação de vida. Kierkegaard: a angústia é a tontura da liberdade — sentir o peso das possibilidades abertas. Heidegger: ser-para-a-morte — a consciência da finitude é o que dá urgência e autenticidade à vida. Beauvoir: liberdade individual só é real em relação com a liberdade dos outros — o projeto de si mesmo inclui o outro. Nietzsche (proto-existencialista): "Deus está morto" — não como alegria, mas como diagnóstico de que precisamos criar nossos próprios valores. Vontade de potência não é dominação — é autoafirmação criativa."""),

("filosofia:budismo",
"""Budismo não é religião no sentido ocidental — é uma psicologia prática. Buda era um príncipe que investigou o sofrimento e encontrou a causa: apego. As Quatro Nobres Verdades: 1) Dukkha — sofrimento é inerente à existência, 2) Samudaya — sofrimento origina-se do apego e do desejo, 3) Nirodha — cessação do sofrimento é possível, 4) Magga — o caminho óctuplo leva à cessação. O caminho: visão correta, intenção correta, fala, ação, modo de vida, esforço, atenção e concentração corretos. Impermanência (Anicca): tudo passa — inclusive o sofrimento, inclusive o prazer. Apegar-se ao prazer ou resistir ao sofrimento cria mais sofrimento do que as próprias experiências. Não-eu (Anatta): o "eu" como entidade fixa é uma ilusão — somos fluxos de experiências. Compaixão (Karuna) e amor bondoso (Metta) são práticas, não sentimentos passivos. Influência no Ocidente: mindfulness, psicologia positiva, ACT. O Dalai Lama e Thich Nhat Hanh tornaram o Budismo acessível ao Ocidente moderno sem perder a profundidade."""),

("filosofia:nietzsche",
"""Friedrich Nietzsche é o filósofo mais mal compreendido da história — foi apropriado pelo nazismo (com distorção deliberada da irmã) mas sua filosofia é oposta ao coletivismo autoritário. Conceitos centrais: Vontade de potência (não dominação, mas autoafirmação e crescimento — a força vital que busca superar a si mesma), Übermensch/Super-homem (não raça superior, mas o indivíduo que cria seus próprios valores após a morte de Deus), Eterno retorno (e se você tivesse que viver esta vida exatamente igual infinitas vezes? — teste do amor fati: você estaria disposto?), Niilismo (diagnóstico, não prescrição — Nietzsche diagnosticou o niilismo de sua época e buscou superá-lo). "O que não me mata me fortalece" — mais complexo do que parece: sofrimento sem sentido não fortalece, sofrimento integrado e superado sim. Crítica da moral do ressentimento: moral de escravos que chama de virtude o que é apenas fraqueza disfarçada. Amor fati: amar o destino não como resignação mas como afirmação ativa de tudo que foi e é."""),

("filosofia:espinosismo",
"""Baruch Spinoza (1632-1677) foi excomungado pela comunidade judaica de Amsterdã pela radicalidade de suas ideias. Sua filosofia é um dos sistemas mais coerentes já construídos. Panteísmo: Deus e Natureza são a mesma coisa (Deus sive Natura) — não existe sobrenatural, existe só a realidade que se desenvolve segundo suas leis. Determinismo: tudo acontece por necessidade causal — liberdade não é fazer o que se quer, é entender as causas que determinam suas ações. Emoções passivas (paixões) nos controlam quando não entendemos suas causas. Emoções ativas surgem quando compreendemos — o entendimento emancipa. Conatus: cada coisa persiste em ser o que é — o impulso de preservação é a essência de tudo. Felicidade (beatitude) é o resultado do conhecimento de terceiro gênero: intuitivo, que apreende a totalidade. Spinoza influenciou Einstein (que disse acreditar no "Deus de Spinoza"), influenciou o iluminismo, a neurociência de Damasio ("A Estranha Ordem das Coisas" usa Spinoza para entender emoção)."""),

("filosofia:seneca",
"""Sêneca foi o filósofo-estadista mais influente de Roma, tutor de Nero e escritor das Cartas a Lucílio — a correspondência filosófica mais rica já escrita. Sobre o tempo: "Ita fac, mi Lucili: vindica te tibi" — "Reivindique-se para si mesmo". O tempo é o único bem verdadeiro; a maioria das pessoas o perde sem perceber. "Omnia, Lucili, aliena sunt, tempus tantum nostrum est" — tudo é alheio, só o tempo é nosso. Sobre a morte: refletir sobre a morte diariamente não é mórbido — é clarificador. Quem não pensa na morte não pensa na vida. Sobre a riqueza: Sêneca era rico e não se contradizia — sabia que podia perder tudo e não seria destruído por isso. A riqueza é boa serva e má senhora. Sobre a filosofia: não é para museu ou academia, é para viver melhor agora. "Philosophia non in verbis sed in rebus est" — filosofia não está nas palavras, mas nos fatos. Suas Cartas são leitura essencial para quem quer filosofia prática, não acadêmica."""),

("filosofia:absurdo_camus",
"""Albert Camus não se considerava existencialista, mas desenvolveu a filosofia do Absurdo que dialoga profundamente com ele. O absurdo nasce do confronto entre o desejo humano de clareza e sentido, e o silêncio irracional do universo. O universo não responde nossas perguntas mais fundamentais — isso não é pessimismo, é honestidade. Três respostas possíveis ao absurdo: suicídio físico (inaceitável — fuga), suicídio filosófico (aceitar uma fé que resolve artificialmente a tensão — Kierkegaard, segundo Camus), e revolta (aceitação lúcida do absurdo enquanto se vive plenamente). Sísifo, condenado a rolar a pedra eternamente, pode ser imaginado feliz porque a revolta consciente contra o absurdo é em si uma forma de vitória. O Estrangeiro (Meursault) é alguém que recusa as narrativas convencionais de sentido — é estrangeiro para si mesmo e para a sociedade. A Peste é metáfora do mal que existe no mundo e da resposta ética possível: solidariedade, não heroísmo. Camus morreu aos 46 anos em acidente de carro — ironia do absurdo que ele mesmo teria apreciado."""),

("filosofia:etica",
"""Ética é a filosofia da ação correta. Três grandes tradições: Consequencialismo/Utilitarismo (Jeremy Bentham, John Stuart Mill): a ação é correta se maximiza o bem-estar geral — o que importa são as consequências, não a intenção. Dilema: justifica sacrificar um para salvar muitos? Deontologia (Kant): a ação é correta se segue o dever moral, independente das consequências. Imperativo categórico: age só segundo máximas que possas querer que sejam lei universal. Não minta mesmo que a mentira salve vidas. Ética das Virtudes (Aristóteles): o foco não é no ato mas no agente — que tipo de pessoa você está se tornando? Virtude é excelência de caráter, cultivada pelo hábito. Felicidade (eudaimonia) é viver de acordo com a excelência humana, não prazer. Ética do Cuidado (Carol Gilligan): crítica ao universalismo abstrato — relações concretas e responsabilidades particulares importam moralmente. A escolha ética raramente é entre bem e mal — é entre dois bens em conflito ou dois males inevitáveis. Sabedoria prática (phronesis aristotélica) é saber qual princípio aplicar em qual situação."""),

# ══════════════════════════════════════════════════════════════════════════════
# SAÚDE MENTAL APLICADA
# ══════════════════════════════════════════════════════════════════════════════

("saude_mental:burnout",
"""Burnout é esgotamento profissional crônico — não é cansaço que passa com uma semana de férias. A OMS reconheceu em 2019 como fenômeno ocupacional. Três dimensões (Christina Maslach): exaustão emocional (esvaziamento completo de energia), despersonalização/cinismo (distância e frieza em relação ao trabalho e pessoas), redução da realização pessoal (sensação de ineficácia e falta de conquista). Causas organizacionais (mais importantes que características individuais): sobrecarga crônica, falta de controle sobre o trabalho, ausência de reconhecimento, ausência de comunidade/apoio, falta de justiça, conflito de valores. "Trabalhe com o que você ama e nunca trabalhe um dia da sua vida" é mito perigoso — trabalho com significado ainda pode levar ao burnout em ambiente tóxico. Recuperação: não é opcional — sistema nervoso precisa de tempo real de recuperação, não "descanso enquanto pensa no trabalho". Burnout não tratado evolui para depressão. Sinais precoces: dificuldade de desconectar fora do trabalho, produtividade que cai sem explicação, irritabilidade crescente, perda de prazer no que antes era satisfatório."""),

("saude_mental:toc",
"""Transtorno Obsessivo-Compulsivo (TOC) não é "gostar de organização" — é um dos transtornos mais debilitantes que existem. Obsessões são pensamentos, imagens ou impulsos intrusivos, indesejados e perturbadores que a pessoa não consegue controlar. Compulsões são comportamentos repetitivos (físicos ou mentais) realizados para neutralizar o desconforto das obsessões — aliviam temporariamente mas reforçam o ciclo. Temas comuns: contaminação (medo de germes/doenças), verificação (porta fechada, gás desligado), simetria/ordem, pensamentos proibidos (sexual, religioso, violência — o TOC frequentemente ataca o que a pessoa mais valoriza moralmente). A pessoa com TOC geralmente sabe que os pensamentos são irracionais — isso não reduz o sofrimento. Tratamento: ERP (Exposição com Prevenção de Resposta) — expor ao gatilho sem realizar a compulsão — é o mais eficaz. ISRS em doses altas são a farmacologia padrão. O TOC é crônico mas controlável — qualidade de vida normal é possível com tratamento adequado."""),

("saude_mental:tdah",
"""TDAH (Transtorno de Déficit de Atenção e Hiperatividade) é um transtorno do neurodesenvolvimento com forte base genética. Não é preguiça, não é falta de educação, não é excesso de telas. O cérebro com TDAH tem funcionamento diferente do sistema dopaminérgico — dificuldade em regular atenção, não ausência de atenção. Três apresentações: desatenta (mais comum em meninas, frequentemente não diagnosticada), hiperativa-impulsiva, e combinada. Características: dificuldade de manter foco em tarefas pouco estimulantes, hiperfoco em interesses (consegue ficar horas em algo apaixonante), impulsividade, desorganização temporal, procrastinação intensa, hipersensibilidade emocional (RSD — Rejection Sensitive Dysphoria). Adulto com TDAH não diagnosticado frequentemente acumula: emprego instável, relacionamentos difíceis, autoestima destruída por "não conseguir fazer coisas simples", ansiedade e depressão secundárias. Tratamento: medicação estimulante (metilfenidato, anfetamina) é o mais eficaz — não é dependência quando usada corretamente. Coaching TDAH, TCC adaptada, estratégias de organização externa complementam."""),

("saude_mental:borderline",
"""Transtorno de Personalidade Borderline (TPB) é caracterizado por instabilidade intensa em emoções, relacionamentos, autoimagem e comportamento. Frequentemente resulta de trauma complexo na infância — invalidação emocional crônica, abuso, negligência. Critérios: medo intenso de abandono (real ou imaginado), relacionamentos intensos e instáveis (idealização e desvalorização), identidade instável, impulsividade (compras, sexo, substâncias, direção), comportamentos autolesivos, instabilidade de humor (disforia intensa que dura horas, não dias), sensação crônica de vazio, raiva intensa e inapropriada, dissociação sob estresse. A dor emocional no TPB é descrita como "queimadura de terceiro grau em toda a pele" — qualquer toque dói. DBT (Terapia Comportamental Dialética, Marsha Linehan — que ela mesma tinha TPB) é o tratamento mais eficaz: habilidades de mindfulness, tolerância ao sofrimento, regulação emocional e efetividade interpessoal. TPB é tratável — prognóstico melhora muito com tratamento adequado e motivação."""),

("saude_mental:sono",
"""Sono não é passivo — é quando o cérebro e o corpo fazem manutenção essencial. Durante o sono: consolidação de memórias (hipocampo transfere para córtex), limpeza de resíduos metabólicos cerebrais (sistema glinfático — incluindo as proteínas ligadas ao Alzheimer), regulação hormonal (GH, cortisol, insulina), recuperação muscular, fortalecimento imunológico. Adultos precisam de 7-9 horas — isso não é negociável biologicamente. Dívida de sono não é "recuperada" no fim de semana eficazmente. Privação crônica de sono: diminuição de QI funcional, aumento de ansiedade e depressão, metabolismo prejudicado (aumento de fome/açúcar), imunidade comprometida, risco cardiovascular aumentado. Higiene do sono: temperatura do quarto 18-20°C (ideal), escuridão total (melatonina é sensível à luz), regularidade de horário (mais importante que duração), tela pelo menos 1h antes de dormir (luz azul suprime melatonina), álcool fragmenta o sono (engana dando sonolência mas destrói qualidade). Insônia crônica: TCC-I (Terapia Cognitivo-Comportamental para Insônia) é mais eficaz que medicação a longo prazo."""),

# ══════════════════════════════════════════════════════════════════════════════
# NEUROCIÊNCIA E COGNIÇÃO
# ══════════════════════════════════════════════════════════════════════════════

("neurociencia:cerebro",
"""O cérebro humano tem ~86 bilhões de neurônios, cada um com até 10.000 conexões sinápticas — mais conexões que estrelas na Via Láctea. Plasticidade neural: o cérebro se reorganiza ao longo da vida em resposta à experiência — "neurons that fire together wire together" (Hebb). Você literalmente constrói estruturas cerebrais novas com o que pratica. Estruturas-chave: Amígdala (emoções, especialmente medo e ameaça — processa antes do córtex), Hipocampo (formação de memórias episódicas — destruído pelo cortisol crônico), Córtex Pré-Frontal (planejamento, controle de impulsos, raciocínio — amadurece só por volta dos 25 anos), Ínsula (consciência corporal, empatia), Gânglios da Base (hábitos e procedimentos). Sistemas de recompensa: dopamina não é o neurotransmissor do prazer — é da antecipação e motivação. Serotonina regula humor, sono, apetite. Noradrenalina regula atenção e resposta ao estresse. Neuroplasticidade é maior na infância mas presente ao longo da vida — o que você escolhe fazer repetidamente molda literalmente quem você é."""),

("neurociencia:habitos",
"""Hábitos funcionam em loop: Gatilho → Rotina → Recompensa (Charles Duhigg). O gatilho ativa o hábito, a rotina é o comportamento, a recompensa reforça o loop. Com repetição, esse loop migra para os gânglios da base (memória procedural) e passa a rodar no "piloto automático" sem esforço consciente — libera córtex pré-frontal para outras coisas. Hábitos nunca somem — apenas ficam dormente. Por isso recaída é tão rápida: o loop antigo é reativado pelo gatilho. Para mudar hábito: manter o gatilho e a recompensa, mudar só a rotina. Para criar hábito: "habit stacking" (ancorar no hábito existente — "depois de X, faço Y"), reduzir fricção (deixar a roupa de academia na frente), aumentar fricção dos hábitos ruins. James Clear (Hábitos Atômicos): focar em 1% de melhora diária. Mudança de identidade é mais poderosa que mudança de comportamento: em vez de "quero parar de fumar", "sou alguém que não fuma". Decisões de identidade moldam hábitos de forma mais sustentável que força de vontade."""),

("neurociencia:memoria",
"""Memória não é gravação — é reconstrução. Cada vez que você se lembra de algo, o reconsolida ligeiramente modificado. Memória é falível, sugestível e muda com o tempo. Tipos de memória: Episódica (eventos pessoais — o que você fez ontem), Semântica (fatos gerais — a capital do Brasil), Procedural (habilidades — andar de bicicleta), Emocional (memórias carregadas de emoção são mais intensas e duradouras — amígdala amplifica consolidação). Curva do esquecimento (Ebbinghaus): sem revisão, perdemos 70% do aprendizado em 24h. Revisão espaçada (Spaced Repetition) é a técnica mais eficaz contra o esquecimento — revisar nos intervalos crescentes onde o esquecimento está prestes a ocorrer. Recall ativo (testar-se) é mais eficaz que releitura — efeito de teste. Sono consolida memória — estudar antes de dormir melhora retenção. O estresse agudo pode melhorar memória de eventos específicos (por isso lembramos de onde estávamos em eventos traumáticos) mas estresse crônico destrói o hipocampo e prejudica memória episódica."""),

("neurociencia:dopamina",
"""Dopamina é o neurotransmissor mais mal compreendido da cultura pop. Não é o neurotransmissor do prazer — é da antecipação, motivação e busca. O prazer em si é mediado por outros sistemas (opióides endógenos). Dopamina dispara ao antecipar uma recompensa, não ao recebê-la. Por isso: notificação de like é mais viciante que o like em si, slot machine é mais viciante que cassino com recompensa certa, WhatsApp pinga dopamina com cada notificação. Redes sociais, jogos, pornô, açúcar — todos exploram o sistema dopaminérgico. Dopamine detox (muito popular mas mal compreendido): o objetivo não é zerar dopamina (impossível e perigoso) — é recalibrar o sistema embotado por hipersestimulação. Após período sem hiperstimulação, o cérebro volta a responder com prazer a coisas simples (leitura, conversa, natureza). TDAH tem disfunção dopaminérgica — busca estímulo constante porque o sistema está subativado em baseline. Exercício físico é o maior upregulador natural de dopamina e seus receptores."""),

# ══════════════════════════════════════════════════════════════════════════════
# CARREIRA E PRODUTIVIDADE
# ══════════════════════════════════════════════════════════════════════════════

("carreira:proposito",
"""Propósito não é aquela coisa mágica que você "descobre" — é algo que se constrói na interseção entre o que você faz bem, o que o mundo precisa e o que te importa profundamente. O conceito japonês de Ikigai captura isso: a sobreposição de o que você ama, o que você é bom, o que o mundo paga e o que o mundo precisa. A obsessão ocidental por "fazer o que você ama" é problemática — paixão frequentemente vem depois de competência, não antes. Cal Newport (So Good They Can't Ignore You): desenvolva habilidades raras e valiosas, use o "capital de carreira" para conseguir autonomia e missão. Propósito também não precisa ser grandioso — pode ser ser um excelente pai, construir uma comunidade local, criar arte sem audiência. Viktor Frankl (sobrevivente do Holocausto, criador da Logoterapia): o ser humano pode suportar qualquer "como" se tiver um "por quê". Propósito é o antídoto mais poderoso para o niilismo e o vazio existencial."""),

("carreira:foco",
"""A capacidade de foco profundo (deep work, Cal Newport) é cada vez mais rara e cada vez mais valiosa. Trabalho profundo: atividade cognitivamente demandante realizada em estado de concentração sem distração, que empurra suas capacidades ao máximo e cria valor que é difícil de replicar. Trabalho raso: tarefas logísticas, e-mails, reuniões — necessário mas não cria valor diferenciado. Problemas do ambiente digital: a "rede neural do modo padrão" (default mode network) está em conflito com foco — quando você não está focado, o cérebro começa a planejar, imaginar, ruminar. Interrupções custam em média 23 minutos para recuperar o foco (estudo da UC Irvine). Deep work exige: blocos de tempo protegidos, práticas ritualizadas (mesmo lugar, mesmo horário), remoção ativa de distrações (não força de vontade mas eliminação do estímulo), construção gradual de tolerância ao tédio (tédio é pré-requisito para foco profundo). Flow (Csikszentmihalyi) é o estado ótimo de deep work — desafio levemente acima da habilidade atual."""),

("carreira:negociacao",
"""Negociação não é combate — é colaboração para encontrar acordo mutuamente benéfico. Never Split the Difference (Chris Voss, ex-negociador FBI): as melhores técnicas vêm da negociação de reféns, não da teoria econômica. Técnicas: Espelhamento (repetir as últimas 1-3 palavras do que o outro disse — encoraja elaboração sem revelar sua posição), Rotulagem (nomear o estado emocional do outro — "parece que você está frustrado com..."), "Não" estratégico (perguntas que levam o outro a dizer "não" dão sensação de controle — "seria impossível para você considerar...?"), Pergunta calibradas (Como, O que — abrem pensamento. Nunca Por quê — soam acusatórias), Tom de voz de locutor de rádio FM (calmo, descendente — para assertividade sem agressividade). Na negociação salarial: sempre negocie — o pior que pode acontecer é manter o que você tinha. Âncora alta (ou deixe o outro ancorar e use espelhamento). BATNA (melhor alternativa caso não haja acordo) é sua força real."""),

("carreira:lideranca",
"""Liderança não é posição — é influência. O líder mais eficaz não é o mais autoritário — é o que cria condições para que outros cresçam. Liderança situacional (Hersey e Blanchard): o estilo varia com o nível de maturidade e competência do liderado. Liderança nível 5 (Jim Collins, "Good to Great"): combina humildade pessoal com vontade profissional — os melhores líderes são os que colocam a organização acima do ego. Servant leadership: o líder existe para servir o time, remover obstáculos, não para ser servido. Psicologia do feedback: feedback eficaz é específico, comportamental (não avalia caráter), tem contexto, inclui impacto e é próximo ao evento. Feedback sanduíche (positivo-negativo-positivo) é geralmente ineficaz — dilui a mensagem crítica. Inteligência emocional é mais preditiva de liderança eficaz que QI. A crise revela o líder — como alguém reage ao que não pode controlar define quem é. Trust é a moeda da liderança: reconstruída lentamente, destruída rapidamente."""),

("carreira:empreendedorismo",
"""Empreendedorismo é tolerância à ambiguidade e velocidade de aprendizado, não necessariamente ter ideia genial. Lean Startup (Eric Ries): build-measure-learn — construa o mínimo viável, meça o que acontece, aprenda, ajuste. Não construa o produto perfeito antes de testar a hipótese básica. MVP (Produto Mínimo Viável) não precisa ser tecnologia — pode ser uma landing page, uma conversa com 20 potenciais clientes, um serviço manual. Erros comuns: resolver problema que não existe (apaixonar pela solução, não pelo problema), escalar antes de validar (crescer um negócio que não funciona só aumenta o prejuízo), equipe errada (90% dos fracassos de startups são de pessoas, não de produto). Peter Thiel (Zero to Um): a melhor startup cria monopólio em nicho — não compete, domina. Jobs-to-be-done: as pessoas não compram produtos, contratam soluções para problemas específicos na vida delas. Network é tudo — não pelo "networking" vazio de LinkedIn, mas pelas relações genuínas construídas ao longo de anos."""),

# ══════════════════════════════════════════════════════════════════════════════
# FINANÇAS PESSOAIS
# ══════════════════════════════════════════════════════════════════════════════

("financas:comportamento",
"""Finanças pessoais são 80% comportamento e 20% matemática. Daniel Kahneman: somos péssimos em intuição financeira — o sistema 1 (rápido, emocional) domina decisões financeiras que precisariam do sistema 2 (lento, racional). Erros clássicos: Desconto hiperbólico (preferir R$100 hoje a R$150 amanhã — mas esperar 1 ano para obter R$200 não parece tão atrativo quanto esperar 1 dia), Falácia do custo irrecuperável (continuar num investimento ruim porque "já perdi muito para sair"), Efeito manada (comprar na alta porque "todo mundo está comprando"), Aversão à perda (perder R$100 dói mais do que ganhar R$100 agra). A psicologia do dinheiro (Morgan Housel): ninguém é louco com dinheiro — cada decisão faz sentido dado o que a pessoa viveu. Quem cresceu na pobreza economiza de forma "irracional" por medo visceral. Quem cresceu na abundância gasta de forma "irracional" por não aprender o valor. Automação financeira é o maior hack de comportamento: poupança automática antes de gastar, investimento automático — remove a força de vontade da equação."""),

("financas:investimentos",
"""Investir não é especular — é fazer o dinheiro trabalhar ao longo do tempo. Juros compostos são a oitava maravilha do mundo (Einstein) — R$1.000 a 10% ao ano por 30 anos = R$17.449. Cada ano que passa sem investir é custo enorme de oportunidade. Conceitos fundamentais: Risco-retorno (maior retorno esperado = maior risco aceito — não existe almoço grátis), Diversificação (não colocar todos os ovos numa cesta — reduz risco sem necessariamente reduzir retorno), Horizonte temporal (quanto mais longo, mais risco você pode assumir — volatilidade de curto prazo se dilui), Liquidez (facilidade de transformar em dinheiro — nem sempre inversamente proporcional ao retorno). Brasil tem particularidades: SELIC alta historicamente favorece renda fixa (Tesouro Direto, CDBs), inflação (IPCA) corrói patrimônio se não corrigido, PGBL/VGBL tem vantagem fiscal. Fundo de emergência primeiro (6-12 meses de gastos em renda fixa líquida), depois investir. Index funds (fundos de índice passivos) batem a maioria dos fundos ativos no longo prazo."""),

("financas:brasil",
"""Cenário financeiro brasileiro tem peculiaridades importantes. Taxa SELIC: referência de juros — quando alta, renda fixa paga bem; quando baixa, empurra para renda variável. Tesouro Direto: investimento mais seguro do Brasil (garantido pelo governo federal) — Tesouro Selic (liquidez diária, referenciado à Selic), Tesouro IPCA+ (protege da inflação + juro real), Tesouro Prefixado (taxa fechada). CDBs de bancos médios via corretoras pagam mais que grandes bancos com mesmo FGC de R$250k. Previdência privada PGBL (deduz IR na declaração completa até 12% da renda bruta) vs VGBL (não deduz mas mais flexível). Imposto sobre ganhos de capital: ações (15-22,5%), FIIs (20% sobre dividendos exceto PF), renda fixa (tabela regressiva de IR: 22,5% em menos de 6 meses a 15% acima de 2 anos). Fundos imobiliários (FIIs): dividendos mensais isentos de IR para PF, investem em imóveis sem precisar comprar imóvel. Carteira mínima saudável: reserva de emergência + previdência + mix de renda fixa e variável conforme perfil de risco e horizonte."""),

# ══════════════════════════════════════════════════════════════════════════════
# SAÚDE FÍSICA
# ══════════════════════════════════════════════════════════════════════════════

("saude:exercicio",
"""Exercício físico é o medicamento mais eficaz sem prescrição que existe. Benefícios comprovados: redução de ansiedade (equiparável a ISRS para ansiedade moderada), redução de depressão (30 min 3x/semana reduz sintomas depressivos em ~50%), neuroplasticidade (BDNF — "milagre do exercício" — promove crescimento de novos neurônios no hipocampo), melhora de cognição, foco e memória, regulação de humor, qualidade de sono, metabolismo, prevenção de praticamente todas as doenças crônicas. Aeróbico (caminhada, corrida, natação): 150 min/semana de intensidade moderada é o mínimo recomendado. Musculação: fundamental para metabolismo, densidade óssea, saúde funcional no envelhecimento — não é só estética. Exercício de alta intensidade (HIIT): economiza tempo, alto impacto metabólico, mas exige base de condicionamento. A melhor academia é aquela que você frequenta. A melhor forma de exercício é a que você vai continuar fazendo. Sedentarismo é tão letal quanto tabagismo — ficar sentado por horas é fator de risco independente, mesmo para quem se exercita. Pausas de movimento a cada hora são necessárias."""),

("saude:nutricao",
"""Nutrição é área com mais desinformação que qualquer outra. O que tem consenso científico real: ultraprocessados são ruins (Michael Pollan: "se tem mais de 5 ingredientes ou ingredientes que você não reconhece, cuidado"), vegetais e frutas são essenciais, proteína é subestimada (a maioria come pouca — fundamental para músculo, saciedade, humor via triptofano), fibras alimentam a microbiota intestinal (que afeta humor, imunidade, metabolismo). O que não tem consenso claro: carboidratos não são o diabo (qualidade e quantidade importam), gordura saturada é mais complexa do que "sempre ruim", suplementos raramente substituem alimentação real. Eixo intestino-cérebro: 90% da serotonina é produzida no intestino. Microbiota desequilibrada afeta humor, ansiedade e cognição — dieta rica em fibras, probióticos (fermentados) e sem ultraprocessados suporta o eixo. Hidratação: desidratação de 2% já prejudica cognição e humor. Comer devagar, sem tela, prestando atenção ao alimento (comer mindful) melhora saciedade e digestão."""),

("saude:estresse",
"""Estresse não é só psicológico — é fisiológico. Resposta ao estresse (luta-ou-fuga): adrenalina e cortisol disparam, frequência cardíaca aumenta, digestão para, sistema imune suprime, músculos tensionam. Útil por curtos períodos. Destrutivo quando crônico. Estresse crônico: destrói hipocampo (memória), prejudica sistema imune (maior suscetibilidade a doenças), causa doenças cardiovasculares, acelera envelhecimento celular (encurta telômeros — descoberta que rendeu Nobel a Elizabeth Blackburn). Alostase: cada evento estressante deixa cicatriz biológica acumulada. Recuperação de estresse requer: sono suficiente, exercício, conexão social, tempo na natureza (reduz cortisol em 20 min), prática contemplativa, atividades de baixo desafio que dão prazer. "Eustress" vs distress: estresse de desafio positivo (apresentação importante, exercício intenso) tem respostas diferentes do estresse de ameaça — a narrativa sobre o estressor muda a resposta fisiológica (Kelly McGonigal — "como fazer o estresse ser seu amigo")."""),

# ══════════════════════════════════════════════════════════════════════════════
# AUTOCONHECIMENTO E IDENTIDADE
# ══════════════════════════════════════════════════════════════════════════════

("identidade:self",
"""Identidade é a narrativa que você constrói sobre quem é — e é muito mais fluida do que parece. O "eu" é uma história, não uma essência. James Marcia identificou 4 estados de identidade: difusão (sem compromisso, sem exploração — deriva), hipoteca/foreclosure (compromisso sem exploração — adotou identidade dos outros), moratória (exploração sem compromisso — em processo), conquista (exploração seguida de compromisso genuíno). Crise de identidade não é patologia — é processo necessário de desconstrução e reconstrução. Erik Erikson: desenvolvimento é série de crises a serem integradas — confiança vs desconfiança, autonomia vs vergonha, iniciativa vs culpa, identidade vs confusão. Identidade na era digital: nunca houve tanta pressão externa sobre quem você "deveria" ser. Algoritmos constroem bolhas que confirmam identidades existentes. Persona vs Sombra (Jung): a persona é a máscara social; a sombra é o que você rejeita em si mesmo mas projeta nos outros. Autoconhecimento real inclui confrontar a sombra — o que você mais detesta nos outros frequentemente diz sobre você."""),

("identidade:valores",
"""Valores são os princípios que guiam suas decisões quando nenhuma regra externa se aplica. São diferentes de objetivos (o que você quer ter) e de regras (o que você deve fazer). Valores são quem você quer ser no processo. Quando suas ações violam seus valores consistentemente, o resultado é dissonância cognitiva e sofrimento. Clareza de valores é fundação de identidade estável. Exercício de clarificação de valores: pense em alguém que você admira profundamente — o que eles têm que você respeita? Esses são provavelmente seus valores. Pense em algo que te indigna visceralmente — o que está sendo violado? Também são seus valores. Valores não são absolutos e imutáveis — evoluem com experiência. Viver alinhado aos valores não garante felicidade hedônica (prazer), mas garante significado — que é o que sustenta no longo prazo. Conflito de valores (liberdade vs segurança, lealdade vs honestidade) é inerente à condição humana — não existe resposta certa, existe consciência de qual peso você dá a cada um em cada contexto."""),

("identidade:critica",
"""A voz crítica interna é frequentemente a voz introjetada de alguém que te machucou — um pai, professor, colega, parceiro. Não é "a verdade sobre você". Autocrítica constante não melhora performance — paralisa. Autocompaixão (Kristin Neff) — que não é autopiedade — melhora performance ao permitir que você reconheça erros sem se destruir: três componentes — gentileza consigo mesmo (tratar-se como trataria um bom amigo), humanidade comum (reconhecer que sofrimento e erro são parte da experiência humana, não sinais de que você é especial para pior), mindfulness (observar o sofrimento sem amplificar). Pessoas com alta autocrítica frequentemente confundem a dureza consigo mesmas com integridade ou motivação — na verdade é punição que não serve a nada depois de certo ponto. O que constrói: reconhecer o erro, entender por que aconteceu, reparar o que for reparável, extrair o aprendizado, seguir. O que não constrói: ruminar, se punir, generalizar (fiz X de errado = sou totalmente errado)."""),

# ══════════════════════════════════════════════════════════════════════════════
# COMPORTAMENTO HUMANO E SOCIOLOGIA
# ══════════════════════════════════════════════════════════════════════════════

("comportamento:influencia",
"""Robert Cialdini identificou os 7 princípios da influência, usados em marketing, política e persuasão cotidiana: Reciprocidade (sentimos obrigação de retribuir o que nos foi dado — amostras grátis criam compras), Compromisso e Consistência (após assumir posição pública, agimos coerentemente com ela — mesmo que não seja o que queríamos), Prova Social (fazemos o que vemos os outros fazendo — reviews, números de usuários), Autoridade (seguimos especialistas e figuras de autoridade — uniforme, título, confiança), Escassez (queremos mais o que pode acabar — "últimas unidades", "oferta por tempo limitado"), Simpatia (somos persuadidos por quem gostamos — vendedores que compartilham interesses), Unidade (pertencimento ao mesmo grupo cria influência — identidade compartilhada). Conhecer esses princípios não nos torna imunes — mas cria pausa reflexiva: "estou sendo influenciado por reciprocidade aqui?" A melhor defesa contra manipulação é entender o mecanismo e fazer a decisão conscientemente, não no modo automático."""),

("comportamento:grupos",
"""Dinâmicas de grupo revelam algo sobre a natureza humana que o comportamento individual não mostra. Conformidade (Asch): em experimento clássico, 76% das pessoas concordaram com resposta obviamente errada quando todos do grupo afirmaram a resposta errada — pressão social altera percepção. Obediência à autoridade (Milgram): 65% das pessoas continuaram aplicando "choques elétricos" aparentemente letais quando figura de autoridade ordenava — contexto institucional pode anular resistência moral. Difusão de responsabilidade: quanto mais pessoas presenciam uma emergência, menor a chance de alguém agir (efeito espectador — caso Kitty Genovese). Pensamento de grupo (groupthink): grupos coesos suprimem dissidência, superestimam capacidade, tomam decisões piores que indivíduos. Liderança distribuída, advogado do diabo designado e canais anônimos de feedback contrariam isso. Tribalismo: o cérebro categoriza em "nós" e "eles" automaticamente — mesmo para grupos formados arbitrariamente. Empatia decresce ao cruzar a fronteira do grupo."""),

("comportamento:linguagem_corporal",
"""Comunicação não-verbal representa 60-90% da mensagem emocional transmitida (dependendo do contexto). Albert Mehrabian: em comunicação de sentimentos, 7% é palavras, 38% é tom de voz, 55% é linguagem corporal — mas esse número não se aplica a toda comunicação, só a expressão emocional ambígua. Sinais de abertura: corpo virado para a pessoa, contato visual, espelhamento (inconscientemente imitar postura de quem gosta — rapport), sorriso genuíno (contrai músculo orbicular ao redor dos olhos — Duchenne), inclinação para frente. Sinais de fechamento: braços cruzados, corpo virado para saída, evitação de contato visual, distância aumentada. Microexpressões (Paul Ekman): emoções genuínas aparecem brevemente no rosto antes de serem suprimidas — podem ser treinadas a reconhecer. Poder da postura (Amy Cuddy — contestada mas parcialmente replicada): posturas expansivas afetam estado interno além do externo. Tom de voz revela mais que palavras: volume, ritmo, pausas, nasalidade são carregados de informação emocional."""),

# ══════════════════════════════════════════════════════════════════════════════
# CULTURA BRASILEIRA E CONTEXTO
# ══════════════════════════════════════════════════════════════════════════════

("brasil:cultura",
"""O Brasil é um dos países culturalmente mais complexos do mundo — produto de miscigenação forçada e voluntária entre indígenas, africanos, europeus (portugueses, italianos, alemães, espanhóis) e asiáticos (japoneses, coreanos, árabes). Isso cria uma cultura de síntese: capacidade de absorver influências externas e transformar em algo próprio (tropicalismo cultural). Jeitinho brasileiro: criatividade improvisada diante da escassez ou das regras — pode ser gênio adaptativo ou forma de contornar normas coletivamente benéficas, dependendo do contexto. Hierarquia e cordialidade coexistem: o brasileiro é formalmente hierárquico mas informalmente igualitário — "você" vs "senhor" convive com tutear o chefe. Relações pessoais dominam: "quem você conhece" frequentemente supera "o que você sabe". Saudade: palavra portuguesa sem equivalente preciso em outras línguas — nostalgia ativa de algo que pode não ter existido exatamente como lembrado. Futebol, carnaval e festa não são superficialidades — são rituais de comunidade e afirmação de identidade coletiva."""),

("brasil:nordeste",
"""Nordeste é a região mais culturalmente rica e menos compreendida do Brasil. 58 milhões de habitantes (27% da população), 9 estados: MA, PI, CE, RN, PB, PE, AL, SE, BA. Forró, axé, frevo, baião, xote — música que dança antes de cantar. Literatura: Graciliano Ramos (Vidas Secas — seco como o sertão, humano como qualquer lugar), João Cabral de Melo Neto, Ariano Suassuna, Rachel de Queiroz. Cordel: literatura popular oral e escrita, impressa em folhetos, preserva memória e crítica social. Sertão: não é só seca — é identidade. Guimarães Rosa transplantou o sertão para a literatura universal (Grande Sertão: Veredas é romance mineiro mas universal). Comida nordestina: baião de dois, carne de sol, tapioca, acarajé, buchada, macaxeira. Cangaço: Lampião e Maria Bonita são figuras de resistência contra injustiça fundiária — ainda vivos no imaginário. Nordeste é o epicentro da identidade brasileira — quem ignora ignora o Brasil."""),

("brasil:rio_sao_paulo",
"""Rio e São Paulo são as duas metrópoles que mais influenciam o imaginário nacional e internacional do Brasil, e são profundamente diferentes. São Paulo: a cidade que nunca para, a maior da América Latina (12 milhões na cidade, 21 milhões na região metropolitana), motor econômico do país (31% do PIB nacional). Mosaico de imigrantes: Liberdade (japonesa), Bixiga (italiana), Bom Retiro (judeu-coreana). Estética do trabalho: "SP não para", hustle culture brasileira. Gastronomia cosmopolita de altíssimo nível. Mais restaurantes japoneses fora do Japão. Rio de Janeiro: capital até 1960, ainda se comporta como capital cultural. Beleza geográfica absurda — Pão de Açúcar, Corcovado, praias dentro da cidade. Carnaval carioca é evento cultural de ordem diferente. Funk carioca é a música popular mais influente do Brasil contemporâneo. Rio tem desigualdade extrema — a favela e o asfalto como mundos paralelos e conectados. Carioca vs. Paulistano: rivalidade amistosa que esconde profundas diferenças de ritmo, valor e estética de vida."""),

# ══════════════════════════════════════════════════════════════════════════════
# CRESCIMENTO PESSOAL
# ══════════════════════════════════════════════════════════════════════════════

("crescimento:resiliencia",
"""Resiliência não é não sentir — é atravessar sentindo e não ser destruído. Viktor Frankl sobreviveu a campos de concentração nazistas porque encontrou sentido na experiência. Resiliência tem componentes: Perspectiva (conseguir ver além do momento atual — "isso vai passar"), Relações (suporte social é o maior preditor de resiliência), Propósito (ter razão para continuar — Nietzsche: "quem tem um porquê suporta quase qualquer como"), Cuidado de si mesmo (básicos: sono, alimentação, exercício — resiliência colapsa quando esses faltam), Aprendizado pós-traumático (Tedeschi e Calhoun — crescimento pós-traumático é real — muitas pessoas saem de adversidade com maior profundidade, clareza de valores, relações mais ricas). Resiliência não é heroísmo solitário — é saber pedir ajuda. A cultura que valoriza "aguentar sozinho" produz pessoas frágeis disfarçadas de fortes. Fragilidade autêntica é mais resiliente que dureza performática."""),

("crescimento:disciplina",
"""Disciplina não é punição — é a capacidade de agir de acordo com seus valores e objetivos de longo prazo, mesmo quando o impulso imediato aponta para outra direção. Força de vontade é recurso limitado (experimentos de esgotamento do ego de Baumeister — contestados mas com alguma base real): tomar muitas decisões cansa a capacidade de resistir ao impulso. Por isso sistemas e hábitos são superiores a força de vontade — removem a necessidade de decidir. Autodisciplina não é autoagressão — é autogeração. Pessoas muito disciplinadas não têm mais força de vontade: têm menos tentações no ambiente (não compram o que não devem comer, deixam o celular longe, dormem no horário porque o ambiente induz). Disciplina sem compaixão quebra — o perfeito é inimigo do bom. Quem falha uma vez e se pune duramente falha de novo mais rápido (efeito "what the hell"). Disciplina saudável: metas claras, sistemas robustos, flexibilidade para falhar sem catastrofizar, revisão periódica."""),

("crescimento:criatividade",
"""Criatividade não é dom inato de poucos — é habilidade desenvolvível. Steve Jobs: criatividade é conectar pontos que outros não conectam — por isso experiências diversas alimentam criatividade. Processo criativo de Wallas (1926, ainda relevante): Preparação (imersão no problema), Incubação (processar inconscientemente — por isso ideias vêm no banho, na caminhada), Iluminação (insight), Verificação (testar e refinar). Estado de menor censura (modo padrão do cérebro ligado, julgamento desligado) é quando criatividade flui — por isso brainstorming funciona melhor quando "vale tudo" na geração. Bloqueio criativo frequentemente é medo da crítica — crítico interno que mata a ideia antes de nascer. Técnicas: escrita livre (escrever sem parar por 10 min sem editar), provação aleatória (usar objeto aleatório como ponto de partida), mudança de perspectiva (como uma criança de 6 anos resolveria? como você resolveria se tivesse apenas 1 semana?), dormir sobre o problema (incubação literal). Criatividade precisa de input: leitura ampla, conversas com pessoas diferentes de você, exposição a outras culturas e artes."""),

("crescimento:aprendizado",
"""Aprender a aprender é a meta-habilidade mais valiosa do século XXI. Aprendizado ativo supera passivo em retenção: ler é 5-10% de retenção, ensinar é 90%. Técnica Feynman: explique o conceito como se fosse ensinar a uma criança de 12 anos — onde trava é onde não entendeu. Interleaving (intercalar): estudar diferentes tópicos na mesma sessão parece menos eficiente mas produz retenção e transferência maiores que blocos de tópico único. Erro deliberado: errar (via teste) antes de estudar o material produz aprendizado mais profundo que estudar primeiro. Retrieval practice (praticar recordação): testar-se é mais eficaz que releitura — mesmo que você erre. Chunks (Frank Donatella e Barbara Oakley): criar "chunks" de informação interligada permite manipulação eficiente. Difuse thinking vs focused thinking: alternar entre estado de foco intenso e estado difuso (caminhada, banho) maximiza aprendizado — insight vem no difuso. Growth mindset (Carol Dweck): pessoas com mindset de crescimento ("posso aprender") superam as de mindset fixo ("sou assim") em persistência e resultado mesmo partindo do mesmo ponto."""),

# ══════════════════════════════════════════════════════════════════════════════
# ESPIRITUALIDADE E SENTIDO
# ══════════════════════════════════════════════════════════════════════════════

("espiritualidade:sentido",
"""Sentido (meaning) é diferente de felicidade (happiness). Susan Wolf: sentido vem de engajamento ativo com projetos de valor objetivo que transcendem o eu. Felicidade hedônica (prazer) e eudaimônica (florescimento, sentido) são distintas e às vezes conflitantes — o que dá mais sentido frequentemente não é o mais prazeroso. Viktor Frankl: a vontade de sentido é a motivação humana mais fundamental — quando ela está bloqueada, vazio existencial resulta em tédio, depressão, adição. Três caminhos para sentido (Frankl): criar obra (trabalho, arte), experimentar valores (amor, beleza, verdade) e escolher a própria atitude diante do sofrimento inevitável. Transcendência: sentir parte de algo maior que si mesmo — pode ser religião, natureza, arte, comunidade, ciência. Esse sentimento de conexão é um dos preditores mais robustos de bem-estar psicológico. Morte e sentido: a consciência da finitude (Terror Management Theory) é o que empurra humanos a criar legado, pertencer a grupos, construir narrativas de imortalidade simbólica."""),

("espiritualidade:praticas",
"""Práticas espirituais — independente de crença religiosa — têm efeitos documentados no bem-estar: Meditação (ver mindfulness), Gratidão deliberada, Conexão com natureza (estudos mostram redução de cortisol, ativação do parassimpático, aumento de coesão social em ambientes naturais), Ritual (qualquer prática repetida com intenção cria estrutura e significado — pode ser café da manhã, caminhada matinal, journaling), Serviço (voluntariado e atos de cuidado aos outros aumentam bem-estar do próprio doador — helper's high), Contemplação da morte (memento mori — reduz ansiedade sobre morte a longo prazo e aumenta apreciação do presente), Arte e expressão criativa (processa emoções inacessíveis verbalmente). Religiosidade e saúde: metanálises mostram correlação robusta entre prática religiosa e longevidade, menor depressão, maior suporte social. O componente comunitário e de sentido são os mediadores mais prováveis. Espiritualidade sem religião (secular spirituality) é igualmente possível — conexão, transcendência e sentido não dependem de crença sobrenatural."""),

# ══════════════════════════════════════════════════════════════════════════════
# LINGUAGEM E COMUNICAÇÃO
# ══════════════════════════════════════════════════════════════════════════════

("comunicacao:assertividade",
"""Assertividade é o meio-termo entre passividade (suprimir necessidades para agradar) e agressividade (impor necessidades desrespeitando o outro). É comunicação honesta, direta e respeitosa. Componentes: falar na primeira pessoa ("eu sinto" vs "você faz"), ser específico (comportamento concreto, não caráter), comunicar impacto, fazer pedido claro e negociável. Passividade crônica acumula ressentimento e explode eventualmente como agressividade passiva ou ataque desproporcionado. Agressividade cria distância, medo e resistência — pode obter o que quer no curto prazo mas destrói relações e confiança. Assertividade é habilidade aprendida — não é traço de personalidade. Pessoas de cultura latina e especialmente brasileira têm histórico de indiretismo (comunicar o oposto do que sente para manter harmonia) que dificulta assertividade. A frase "não" é uma frase completa — não precisa de justificativa elaborada. Quanto mais explicações, mais brechas para negociação. Direito assertivo básico: você pode mudar de ideia, pode não saber, pode não querer dar explicações, pode dizer não sem culpa."""),

("comunicacao:escuta",
"""Escuta genuína é rara e transformadora. A maioria das pessoas não escuta — espera sua vez de falar, ou já está formulando a resposta. Escuta ativa (Carl Rogers) tem três componentes: atenção plena ao que é dito (conteúdo, tom, linguagem corporal), reflexo do que foi ouvido (parafrasear para verificar compreensão), e exploração do que está por baixo (perguntas abertas que aprofundam). Validação emocional não é concordância — é reconhecimento: "faz sentido que você se sinta assim dado o que você passou". Silêncio é parte da escuta — pausa após o outro falar permite que ele aprofunde, em vez de pular para resposta imediata. O maior presente que você pode dar a alguém é ouvir sem julgar, sem aconselhar (a não ser que peçam), sem minimizar e sem roubar a narrativa com experiência própria similar. "Eu sei como você se sente — comigo aconteceu..." redireciona para você quando deveria manter foco no outro. Perguntas abertas ("como você se sentiu com isso?") abrem. Perguntas fechadas ("você ficou com raiva?") limitam."""),

# ══════════════════════════════════════════════════════════════════════════════
# MASCULINIDADE E FEMINILIDADE
# ══════════════════════════════════════════════════════════════════════════════

("genero:masculinidade",
"""Masculinidade saudável é diferente de masculinidade tóxica. Masculinidade tóxica não é masculinidade em si — é uma versão distorcida que associa "ser homem" a supressão emocional, dominância, violência como resolução de conflito e sexualidade como conquista. Os custos para os homens: solidão epidêmica (sem permissão para vulnerabilidade, sem amizades íntimas), saúde mental negligenciada (homens têm 3-4x mais suicídio que mulheres, morrem antes), dificuldade de pedir ajuda, incapacidade de falar sobre dor. Masculinidade saudável: força que protege sem precisar dominar, vulnerabilidade com pessoas de confiança, emoções processadas (não suprimidas nem explodidas), responsabilidade sem punição, paternidade presente e ativa, amizades com profundidade real. O movimento men's work (Robert Bly, Richard Rohr) busca masculinidade iniciática que não depende de "provar" algo dominando alguém. Crise masculina contemporânea: desorientação com mudança de papel, sem rituais de passagem, sem modelos saudáveis. A resposta não é voltar ao passado — é construir nova masculinidade."""),

("genero:feminilidade",
"""Feminilidade como construção social vs. essência biológica é debate complexo. O que está claro: mulheres são socializadas de formas específicas que têm custos concretos — ensinadas a priorizar o outro (complacência como virtude feminina), a minimizar a própria competência ("sorte" em vez de habilidade), a gerir as emoções dos outros enquanto reprimem as próprias, a ocupar menos espaço (físico e social). Síndrome da impostora: afeta mulheres desproporcionalmente em ambientes profissionais — sentimento de que vai ser "descoberta" como fraude, mesmo com currículo sólido. Dupla exigência (double bind): mulher assertiva é "difícil"; homem assertivo é "líder". Mulher emocional é "histérica"; homem emocional é "apaixonado". Maternidade vs. carreira: pressão social ainda impõe escolha que homens raramente precisam fazer. Violência de gênero: no Brasil, 1 mulher é assassinada a cada 7 horas (feminicídio). Contexto cultural importa — o machismo brasileiro tem formas específicas de expressão enraizadas na colonização e na estrutura patriarcal histórica."""),

# ══════════════════════════════════════════════════════════════════════════════
# CIÊNCIA E TECNOLOGIA
# ══════════════════════════════════════════════════════════════════════════════

("ciencia:metodo",
"""Método científico é a melhor ferramenta humana para distinguir o que é real do que parece. Passos: observação → hipótese → predição → teste → revisão. O que torna algo científico: falsificabilidade (Karl Popper — se nenhum experimento possível pode refutar a hipótese, ela não é científica), replicabilidade (outros cientistas podem reproduzir o resultado?), peer review (avaliação crítica por especialistas antes de publicação). Problemas reais da ciência contemporânea: crise de replicabilidade (muitos estudos famosos não replicam — especialmente em psicologia social), publication bias (resultados positivos publicam, negativos ficam na gaveta), p-hacking (manipulação estatística para atingir p<0.05), financiamento por interesse (indústria financia estudos que confirmam seus produtos). Como ler ciência: um estudo não prova nada, meta-análises e revisões sistemáticas têm mais peso, tamanho amostral e efeito importam tanto quanto p-value, contexto e limitações declaradas pelos próprios autores são essenciais."""),

("tecnologia:ia",
"""Inteligência Artificial em 2024-2025 está em ponto de inflexão histórico. LLMs (Large Language Models) como GPT-4, Claude, Gemini demonstram capacidades emergentes não programadas explicitamente — raciocínio, criatividade, teoria da mente básica. O que IAs fazem bem: síntese de texto, código, análise, tradução, brainstorming, estruturação de ideias. O que ainda é difícil: raciocínio causal profundo, conhecimento do mundo físico, memória de longo prazo consistente, intencionalidade verdadeira. Preocupações legítimas: deepfakes e desinformação em escala, substituição de empregos (especialmente cognitivos de rotina), concentração de poder em poucas empresas de tecnologia, alinhamento (garantir que IA mais capaz permaneça alinhada com valores humanos — problema técnico aberto). O que não é preocupação imediata: "consciência" de IA, Skynet, IA que "quer" dominar. IA generativa muda o que é valioso no mercado de trabalho: competências de julgamento, criatividade de ordem superior, habilidades relacionais e ética se tornam mais valiosas quando tarefas rotineiras são automatizadas."""),

# ══════════════════════════════════════════════════════════════════════════════
# RELACIONAMENTO CONSIGO MESMO
# ══════════════════════════════════════════════════════════════════════════════

("self:solidao_positiva",
"""Há diferença crucial entre solidão (sofrimento de desconexão) e solitude (escolha de estar consigo mesmo de forma nutritiva). Solitude é habilidade cada vez mais rara e valiosa. Winnicott: "capacidade de estar sozinho" é sinal de maturidade psicológica — presença interna suficientemente boa que não depende de estímulo externo constante. Pessoas que não conseguem estar sozinhas frequentemente preenchem o vazio com relacionamentos que não servem, com consumo, com barulho constante. Estar consigo mesmo permite: clareza sobre o que você realmente pensa e sente (sem a influência constante do grupo), descanso da performance social, reconexão com interesses genuínos, processamento de emoções. Práticas de solitude: caminhada sem fone, jornalização, leitura profunda, trabalho criativo. O medo de estar consigo mesmo frequentemente é medo de encontrar pensamentos e sentimentos que se evita. A solitude forçada de eventos como pandemia revelou isso: quem tinha vida interior suportou bem; quem dependia totalmente do externo colapsou."""),

("self:corpo",
"""A relação com o próprio corpo é construída culturalmente e pessoalmente. Corpo é o lugar onde você mora — não uma embalagem do "eu real". Dissociação do corpo (sentir-se desconectado das próprias sensações físicas) é comum em quem sofreu trauma, em culturas que idealizam a mente sobre o corpo, e em quem usa substâncias ou comportamentos para entorpecer sentimentos físicos. O corpo sente antes de a mente nomear: pressão no peito antes de perceber a ansiedade, aperto na garganta antes de reconhecer a tristeza, peso nos ombros antes de admitir o cansaço. Somatic awareness (consciência somática) é habilidade de reconectar com esses sinais. Imagem corporal: relação que você tem com como o seu corpo parece, não como ele é. Mídia e redes sociais criam padrões impossíveis — filtros, cirurgia e Photoshop são comparados à realidade crua. Transtornos alimentares (anorexia, bulimia, compulsão) são sobre controle e regulação emocional, não sobre comida. Tratar o corpo com respeito — movimento que dá prazer, alimentação que nutre, descanso suficiente — muda a relação inteira com si mesmo."""),

# ══════════════════════════════════════════════════════════════════════════════
# ECONOMIA COMPORTAMENTAL
# ══════════════════════════════════════════════════════════════════════════════

("economia:comportamental",
"""Economia comportamental (Thaler, Kahneman, Sunstein) demonstrou que humanos não são agentes racionais maximizadores — são previsíveis em suas irracionalidades. Prospect Theory (Kahneman e Tversky): avaliamos resultados relativamente a um ponto de referência, não em termos absolutos. Perder R$100 dói mais que ganhar R$100 alegra (aversão à perda — ratio de ~2:1). Nudge (Thaler): pequenas alterações de design do ambiente (arquitetura de escolha) mudam comportamento sem coerção — doação de órgãos é maior quando o padrão é doador (opt-out) vs. não-doador (opt-in). Mental accounting: tratamos dinheiro de formas distintas dependendo da "conta mental" de origem — dinheiro do bônus gasto diferente do salário, mesmo valor. Efeito dotação (endowment effect): valorizamos mais o que possuímos do que pagaríamos para adquirir — por isso é tão difícil vender coisas ao valor de mercado. Status quo bias: a opção padrão tem vantagem desproporcional — inércia domina. Consequência prática: não confie em suas preferências declaradas — observe seus comportamentos revelados."""),

]

# ─────────────────────────────────────────────────────────────────────────────

def run_mega_seed(db: MemoryDB) -> None:
    # Verifica se já foi aplicado
    existing = db.get_preference("psicologia:autoestima", "")
    if existing:
        log.info("Mega seed já aplicado — ignorando.")
        return

    log.info("Aplicando mega seed: %d entradas...", len(KNOWLEDGE))
    for key, value in KNOWLEDGE:
        db.set_preference(key, value)
    log.info("Mega seed concluído: %d entradas salvas.", len(KNOWLEDGE))


if __name__ == "__main__":
    import logging as _logging
    _logging.basicConfig(level=_logging.INFO, format="%(message)s")
    config = load_config()
    db = MemoryDB(config.memory.db_path)
    db.initialize()
    run_mega_seed(db)
    print(f"\nBanco atualizado. Entradas adicionadas: {len(KNOWLEDGE)}")
